#!/bin/bash

FIREFOX_VERSION=$( firefox -version | cut -d " " -f 3 )
DRIVER_LOGLEVEL=${DRIVER_LOGLEVEL:-info}

cat <<_EOF
{
  "capabilities": [
    {
      "version": "$FIREFOX_VERSION",
      "browserName": "firefox",
      "maxInstances": $NODE_MAX_INSTANCES,
      "seleniumProtocol": "WebDriver",
      "applicationName": "$NODE_APPLICATION_NAME",
      "moz:firefoxOptions":
        {
          "log":
            {
              "level": "$DRIVER_LOGLEVEL"
            }
        }
    }
  ],
  "proxy": "com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy",
  "maxSession": $NODE_MAX_SESSION,
  "port": $NODE_PORT,
  "register": true,
  "registerCycle": $NODE_REGISTER_CYCLE,
  "nodePolling": $NODE_POLLING,
  "unregisterIfStillDownAfter": $NODE_UNREGISTER_IF_STILL_DOWN_AFTER,
  "downPollingLimit": $NODE_DOWN_POLLING_LIMIT,
  "hubPort": ${HUB_PORT_PARAM},
  "hubHost": "${HUB_HOST}"
}
_EOF
