#!/bin/bash

CHROME_VERSION=$(/usr/bin/google-chrome -version | awk '{ print $3 }')

cat <<_EOF
{
  "capabilities": [
    {
      "seleniumProtocol": "WebDriver",
      "browserName": "chrome",
      "version": "${CHROME_VERSION}",
      "maxInstances": $NODE_MAX_INSTANCES,
      "platform": "LINUX",
      "applicationName": "$NODE_APPLICATION_NAME"
    }
  ],
  "proxy": "com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy",
  "maxSession": ${NODE_MAX_SESSION},
  "port": ${NODE_PORT},
  "register": true,
  "unregisterIfStillDownAfter": ${NODE_UNREGISTER_IF_STILL_DOWN_AFTER},
  "hubPort": ${HUB_PORT_PARAM},
  "hubHost": "${HUB_HOST}",
  "registerCycle": ${NODE_REGISTER_CYCLE},
  "nodeStatusCheckTimeout": 10000,
  "downPollingLimit": ${NODE_DOWN_POLLING_LIMIT}
}
_EOF
