#!/bin/bash

cat <<_EOF
{
  "theConfigMap": {
    "hub_config_files": [
      "config.json"
    ],
    "auto_start_hub": "1",
    "default_role": "hub",
    "auto_update_drivers": "0",
    "auto_start_node": "0",
    "hub_config": {},
    "log_maximum_age_ms": 864000000,
    "reboot_after_sessions": "0",
    "grid_extras_port": "3000",
    "webdriver": {
      "version": "${CORE_SEL_VERSION_FULL}"
    },
    "node_config_files": []
  }
}
_EOF
